version: "3.3"

networks:
  appnet:
    driver: overlay

services:
  sampleapp:
    image: 127.0.0.1:5000/sampleapp
    build: .
    ports:
      - "80:8080"
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
